двумерные массивы, средняя
annapirova/mp1-2020-382003-2 pull request #35
Opened 2020-12-17 23:53 UTC by vikkkkos

2020-12-23 15:21 UTC, annapirova requested changes
Виктория, пожалуйста, сделайте другую задачу на строки. Эту сдавали уже много раз. Вам - Простая №7 + средняя №6.

2020-12-25 11:54 UTC, vikkkkos commented
где ошибка в 28 задаче по двумерным массивам?

2020-12-25 15:14 UTC, annapirova commented
Виктория, ошибки нет. Надо будет объяснить, что как работает лично.

С уважением,
Анна Пирова

пт, 25 дек. 2020 г., 14:54 Виктория Суслова <notifications@github.com>:

> где ошибка в 28 задаче по двумерным массивам?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/annapirova/mp1-2020-382003-2/pull/35#issuecomment-751238773>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADL2AEPYNVAB25FFYF5SAMDSWR4RFANCNFSM4VANLKWA>
> .
>

2020-12-25 15:19 UTC, annapirova commented
Строка печатается как %s. Не надо цикл писать.

С уважением,
Анна Пирова

пт, 25 дек. 2020 г., 18:14 Anna Pirova <anna.yu.malova@gmail.com>:

> Виктория, ошибки нет. Надо будет объяснить, что как работает лично.
>
> С уважением,
> Анна Пирова
>
> пт, 25 дек. 2020 г., 14:54 Виктория Суслова <notifications@github.com>:
>
>> где ошибка в 28 задаче по двумерным массивам?
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/annapirova/mp1-2020-382003-2/pull/35#issuecomment-751238773>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ADL2AEPYNVAB25FFYF5SAMDSWR4RFANCNFSM4VANLKWA>
>> .
>>
>

2021-04-24 06:13 UTC, closed without merging